<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- Biblioteka do komunikacji z RabbitMQ -->
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
    <!-- Swagger — interfejs do testowania API w przeglądarce -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

</Project>
